# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DornaTest' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DornaTest

	pod 'Alamofire'

  target 'DornaTestTests' do
    inherit! :search_paths
    # Pods for testing

	pod 'Alamofire'
  end

  target 'DornaTestUITests' do
    inherit! :search_paths
    # Pods for testing

	pod 'Alamofire'
  end

end
